apiVersion: v1
kind: ConfigMap
metadata:
  name: os-config
  namespace: default
data:
  data_file: |
    IP=172.31.0.5
    NAME="CentOS Linux"
    VERSION="7 (Core)"
    VERSION_ID="7"

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: example-config
  namespace: default
data:
  example.property.1: hello
  example.property.2: world
  example.property.file: |-
    property.1=value-1
    property.2=value-2
    property.3=value-3