apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment-hostpath
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        kubernetes.io/hostname: node01

      containers:
        - name: nginx
          image: nginx:1.17-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: host-vol

      volumes:
        - name: host-vol
          hostPath:
            path: /host-data

---

apiVersion: v1
kind: Service
metadata:
  name: web-deployment-hostpath-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - nodePort: 30083
      port: 8080
      targetPort: 80