apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: azbykovskyi
spec:
  signerName: kubernetes.io/kube-apiserver-client
  request: put base64 encoded azbykovskyi.csr here
  groups:
  - system:authenticated
  usages:
  - digital signature
  - key encipherment
  - client auth

#To encode azbykovskyi.csr with base64 use following command:
  cat /requests/azbykovskyi/azbykovskyi.csr | base64 | tr -d '\n'

# all the work in done on master only 
