apiVersion: v1
kind: Pod
metadata:
  name: testing-pvc-sc
spec:
  containers:
  - name: busy
    image: busybox
    command:
      - sleep
      - infinity
    volumeMounts:
      - name: sc-pvc
        mountPath: "/data"
  volumes:
    - name: sc-pvc
      persistentVolumeClaim:
        claimName: pvc-with-sc
