apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-with-sc
  namespace: default
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: playpit-labs-storage
