apiVersion: v1
kind: Service
metadata:
  name: service-name
spec:
  selector:
    app: << set the same label as deployment has >>
  ports:
    - protocol: TCP
      # Incoming Port on the Service
      port: 80
      # Incoming Port on Pod(s)
      targetPort: 8080