apiVersion: v1
kind: Service
metadata:
  name: hello-hello-service
spec:
  type: NodePort
  selector:
    app: hello-hello
  ports:
    - nodePort: 31000
      port: 8080
      targetPort: 80