apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2021-08-08T17:29:40Z","generation":1,"labels":{"app":"stranger"},"name":"stranger","namespace":"task-8","resourceVersion":"46334","uid":"fe15915a-f177-499d-aab3-cfe70bbaa141"},"spec":{"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"stranger"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"stranger"}},"spec":{"containers":[{"image":"k8s.gcr.io/pause:3.3","imagePullPolicy":"IfNotPresent","name":"main","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"tolerations":[{"effect":"NoSchedule","key":"env","value":"production"}]}}},"status":{"conditions":[{"lastTransitionTime":"2021-08-08T17:29:40Z","lastUpdateTime":"2021-08-08T17:29:40Z","message":"Deployment does not have minimum availability.","reason":"MinimumReplicasUnavailable","status":"False","type":"Available"},{"lastTransitionTime":"2021-08-08T17:29:40Z","lastUpdateTime":"2021-08-08T17:29:40Z","message":"ReplicaSet \"stranger-759f9cc947\" is progressing.","reason":"ReplicaSetUpdated","status":"True","type":"Progressing"}],"observedGeneration":1,"replicas":2,"unavailableReplicas":2,"updatedReplicas":2}}
  creationTimestamp: "2021-08-08T17:29:40Z"
  generation: 4
  labels:
    app: stranger
  name: stranger
  namespace: task-8
  resourceVersion: "46620"
  uid: fe15915a-f177-499d-aab3-cfe70bbaa141
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: stranger
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stranger
    spec:
      containers:
      - image: k8s.gcr.io/pause:3.3
        imagePullPolicy: IfNotPresent
        name: main
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: env
        value: nonprod
      - key: node
        value: 
        operator: Exists
        effect: NoSchedule
      - key: env
        value: production
        effect: NoSchedule