apiVersion: v1
kind: Pod
metadata:
  name: web-pod-emptydir-tmpfs
  labels:
    app: nginx
spec:
  initContainers:
  - image: busybox
    name: init-busy
    command: ['/bin/sh', '-c']
    args: ['echo "initialized by initContainer, using tmpfs" > /html/index.html']
    volumeMounts:
    - mountPath: /html
      name: shared-pod-volume

  containers:
    - image: nginx:1.17-alpine
      name: nginx
      ports:
        - name: nginx
          containerPort: 80
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: shared-pod-volume

  volumes:
    - name: shared-pod-volume
      emptyDir:
        medium: Memory

---

apiVersion: v1
kind: Service
metadata:
  name: web-pod-emptydir-tmpfs-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - nodePort: 30082
      port: 80
      targetPort: 80