apiVersion: v1
kind: Pod
metadata:
  name: web-tricky-pod-emptydir
  labels:
    app: nginx
spec:
  initContainers:
  - image: busybox
    name: init-busy
    command: ['/bin/sh', '-c']
    args: ['echo -e "Student: Artur Zbykovskyi\n$(MY_POD_NAME)\n$(POD_IP)" > /tmp/web/index.html']
    volumeMounts:
    - mountPath: /tmp/web/
      name: shared-pod-volume
    env:
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP


  containers:
    - image: nginx:1.17-alpine
      name: nginx
      ports:
        - name: nginx
          containerPort: 80
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: shared-pod-volume

  volumes:
    - name: shared-pod-volume
      emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: web-tricky-pod-emptydir-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - nodePort: 30081
      port: 8080
      targetPort: 80