apiVersion: v1
kind: Pod
metadata:
  name: fkpod
  labels:
    repo: fast-k8s
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      env:
        - name: USER
          value: azbykovskyi
