apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  containers:
    - name: envtest
      image: gcr.io/kuar-demo/kuard-amd64:blue
      ports:
        - name: http
          containerPort: 8080
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 2
        failureThreshold: 5