apiVersion: v1
kind: Pod
metadata:
  name: httpd-webserver-pod
  namespace: qa
  labels:
    env: test
    app: httpd
spec:
  containers:
  - name: webserver
    image: httpd:2.4.64-alpine
    imagePullPolicy: Always
    ports:
    - { name: http,  containerPort: 80 }
    - { name: https, containerPort: 443 }
    - name: web
      containerPort: 80
      protocol: TCP