apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
  namespace: default
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600'] 
    command: ['sh', '-c', 'env && sleep infinity']

    command: ["printenv"]
    args: ["HOSTNAME", "KUBERNETES_PORT"]

    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    
    env:
      - name: STUDENT_FIRST_NAME
        value: Artur
      - name: STUDENT_LAST_NAME
        value: Zbykovskyi