#Mounting Secrets Data as Environment variables
apiVersion: v1
kind: Pod
metadata:
  name: email-pod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'leep 4800']
    env:
      - name: EMAIL
        valueFrom:
          secretKeyRef:
            name: devops-secret
            key: email

---
#Using All Secrets Data as Environment Variables
apiVersion: v1
kind: Pod
metadata:
  name: dev-pod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'leep 4800']
    envFrom:
      - secretRef:
          name: devops-secret

---
# Mounting Secrets as Files
apiVersion: v1
kind: Pod
metadata:
  name: dev-volume-pod
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'leep 3600']
    volumeMounts:
      - name: devops-volume
        mountPath: /data/devops-secret

  volumes:
    - name: devops-volume
      secret:
        secretName: devops-secret

        