# file: user-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: user-secrets
type: Opaque
stringData:
  config.yaml: |-
    apiUrl: "https://my.api.com/api/v1"
    username: user
    password: password

    