apiVersion: v1
kind: Pod
metadata:
  name: secret-test-pod
spec:
  restartPolicy: Never
  containers:
  - name: main
    image: k8s.gcr.io/busybox
    resources:
      limits:
        cpu: 1
        memory: 500mb
    command:
    - /bin/sh
    - -c
    - |
      env
      ls -la /etc/config
      cat /etc/config/config.yaml
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: db-user-pass
            key: username
    envFrom:
    - secretRef:
        name: db-user-pass
    volumeMounts:
    - name: user-secrets-volume
      mountPath: "/etc/config"
      readOnly: true
  volumes:
  - name: user-secrets-volume
    secret:
      secretName: user-secrets